// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWmK-X-b9FHJSTgqM_F_Aiv4furntHto8',
    appId: '1:95807489956:web:777f649c5f4be1cc3ce331',
    messagingSenderId: '95807489956',
    projectId: 'firstfirebase-8be1f',
    authDomain: 'firstfirebase-8be1f.firebaseapp.com',
    databaseURL: 'https://firstfirebase-8be1f-default-rtdb.firebaseio.com',
    storageBucket: 'firstfirebase-8be1f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCM9atUtiTF53HmTL8EpM4DSzbtVJHdZFs',
    appId: '1:95807489956:android:93af1193368a0cc13ce331',
    messagingSenderId: '95807489956',
    projectId: 'firstfirebase-8be1f',
    databaseURL: 'https://firstfirebase-8be1f-default-rtdb.firebaseio.com',
    storageBucket: 'firstfirebase-8be1f.appspot.com',
  );
}
